GIN_MODE: debug
Addr: 5555 # 端口号

MySQL:
  User: root
  Password: root
  Host: 192.168.9.60:13306  # 替换为宿主机内网ip
  DBname: test_data
Redis:
  Host: 192.168.9.60:16379
  Password:
  DB: 0  # use default DB


