GIN_MODE: debug
Addr: 5555 # 端口号

MySQL:
  User: root
  Password: root
  Host: 192.168.9.60:13306 // 宿主机ip todo 为什么要用宿主机的ip
  DBname: test_data
Redis:
  Host: 192.168.9.60:16379
  Password:
  DB: 0  # use default DB


