version: '3'

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    image: golang:latest
    container_name: golang-demo
    volumes:
      - $GOPATH/src/github.com/liankui/solitude:/go/src
    ports:
      - 5555:5555
    working_dir: /go/src
    command: go run main.go
    networks:
      network:
        ipv4_address: 177.7.0.12
    depends_on:
      - mysql
      - redis
  mysql:
    image: biarms/mysql:latest
    container_name: mysql-demo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
#    ports:
#      - 13306:3306  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'test_data' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'root' # root管理员用户密码
    volumes:
      - $GOPATH/src/github.com/liankui/solitude/sql:/sql
    networks:
      network:
        ipv4_address: 177.7.0.13
  redis:
    image: redis:latest
    container_name: redis-demo
    restart: always
#    ports:
#      - 16379:6379
    #定义挂载点
    volumes:
      - /usr/local/etc/redis/data:/data
      - /usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      network:
        ipv4_address: 177.7.0.14
    #环境变量
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
