version: '3'
services:
  web:
    image: golang:latest
    container_name: golang-demo
    volumes:
      - $GOPATH/src/github.com/liankui/solitude:/go/src
    ports:
      - 5555:5555
#    network_mode: "host"
#    networks:
#      - testnet
    working_dir: /go/src
    command: go run main.go
  redis:
    image: redis:v7
    container_name: redis-demo
    ports:
      - 6379:6379
    #定义挂载点
    volumes:
      - /usr/local/etc/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    #环境变量
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
