host: localhost:5555
info:
  contact:
    name: Eric
    url: https://github.com/liankui
  description: 一个golang开发的短链接项目
  termsOfService: https://github.com/liankui/solitude
  title: Solitude
  version: "1.0"
paths:
  /expand/{shorten}:
    get:
      consumes:
      - application/json
      description: 使用短链接跳转至原链接
      parameters:
      - description: 短链接
        in: path
        name: shorten
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 短链接字符串
          schema:
            type: string
        "500":
          description: get url error
          schema:
            type: string
      summary: 使用短链接
      tags:
      - url
  /print:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 打印短链接信息
          schema:
            type: string
      summary: 打印最近的一条短链接
      tags:
      - url
  /shorten:
    get:
      consumes:
      - application/json
      description: 使用url参数传递长链接，接口返回短链接
      parameters:
      - description: string valid
        in: query
        name: url
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 短链接字符串
          schema:
            type: string
        "500":
          description: insert mysql error
          schema:
            type: string
      summary: 返回短链
      tags:
      - url
swagger: "2.0"
